version: '3'
services:
  lighthouse-test:
    container_name: lighthouse-test
    image: lighthouse:test
    build:
      context: .
    ports:
      - "7104:8000"
    volumes:
      - .:/home/lighthouse/lighthouse
      - /home/lighthouse/lighthouse/lighthouse.egg-info
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
    entrypoint: "/bin/bash"
    command: >
      -c "../util/wait-for-it.sh db:5432 &&
      alembic -c test.ini upgrade heads &&
      coverage run -m unittest discover &&
      coverage xml"
  db:
    container_name: lighthouse-test-db
    image: postgres:11
    ports:
      - "7105:5432"
    environment:
      - POSTGRES_USER=lighthouse
      - POSTGRES_PASSWORD=testing123
      - POSTGRES_DB=lighthouse-test
