name: Test & Deploy to Docker Hub

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3.7 -m pip install --upgrade pip
          pip3 install setuptools
          pip3 install -e .

      - name: Lint with flake8
        run: |
          pip3 install flake8
          # stop the build if there are Python syntax errors or undefined names
          python3 -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          python3 -m flake8 . --count --exit-zero --statistics

      - name: Test with unittest
        run: docker-compose -f test-compose.yml up --exit-code-from lighthouse-test lighthouse-test
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master

      - name: Login to Docker Hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the image
        run: docker tag lighthouse:test mellow/lighthouse:latest 

      - name: Push to Docker registry
        uses: actions-hub/docker@master
        with:
          args: push mellow/lighthouse:latest
